### PR TITLE
Redo ESP32 partitions.csv parsing

### LINKED ISSUE #61: have error with custom csv
according to the Expressif doc, https://docs.espressif.com/projects/esp-idf/en/v5.3.1/esp32/api-guides/partition-tables.html#creating-custom-tables
a csv can contain spaces and short expressions, like 3M instead of 0x300000.
except that your extension no longer works in this case.

OK with : 
nvs,         data, nvs,     0x9000,  0x5000,
otadata,  data, ota,     0xe000,  0x2000,
app0,      app,  ota_0,   0x10000, 0x300000,
app1,      app,  ota_1,   0x310000,0x300000,
spiffs,     data, spiffs,  0x610000,0x9E0000,
coredump, data, coredump,0xFF0000,0x10000,

KO with : 
nvs,      data, nvs,      0x9000,  0x5000,
otadata,  data, ota,   0xe000,  0x2000,
app0,     app,  ota_0, 0x10000,  3M,
app1,     app,  ota_1,                 ,3M,
spiffs,   data, spiffs,                   ,0x9E0000,
coredump, data, coredump,     ,0x10000,

### PR DESCRIPTION
**Pull request by earlephilhower**
Support comments ('#'), -K and -M modifiers, don't skip 1st line,
and match on the "type" and note "name" fields.   Match "LittleFS"
type, too.

Fixes #61

### CODE REVIEW

**Comment by earlephilhower** [comment]
[test.zip](https://github.com/user-attachments/files/17607804/test.zip)

@stef-ladefense, please exit the IDE, manually remove your current VSIX, and try the one attached in the ZIP file here.  It parses the CSV you attached to the bug, or at least appears to do so for me.

If you could report back that would be appreciated as I'm not a ESP32 user...

**Comment by stef-ladefense** [comment]
> (edit) - Updated version in "test2.zip" to ensure IDE doesn't cache old rev) [test2.zip](https://github.com/user-attachments/files/17607820/test2.zip)
> 
> @stef-ladefense, please exit the IDE, manually remove your current VSIX, and try the one attached in the ZIP file here. It parses the CSV you attached to the bug, or at least appears to do so for me.
> 
> If you could report back that would be appreciated as I'm not a ESP32 user...

hi @earlephilhower you are fast ! 👍🏻 

the 1.3.0 version work with my worse example csv ;)

LittleFS Filesystem Uploader v1.3.0 -- https://github.com/earlephilhower/arduino-littlefs-upload

 Sketch Path: D:\Arduino\ESP32_RadioWeb\ESP32S3_RadioWeb_0_66
   Data Path: D:\Arduino\ESP32_RadioWeb\ESP32S3_RadioWeb_0_66\data
      Device: ESP32 series, model esp32s3
Using partition: partitions.csv in sketch folder
  Partitions: D:\Arduino\ESP32_RadioWeb\ESP32S3_RadioWeb_0_66\partitions.csv
       Start: 0x610000
         End: 0x9f0000

Building LittleFS filesystem
Command Line: C:\Users\Stephane\AppData\Local\Arduino15\packages\esp32\tools\mklittlefs\3.0.0-gnu12-dc7f933\mklittlefs.exe -c D:\Arduino\ESP32_RadioWeb\ESP32S3_RadioWeb_0_66\data -p 256 -b 4096 -s 4063232 C:\Users\Stephane\AppData\Local\Temp\tmp-6364-53B1Z1RPXuOM-.littlefs.bin

Uploading LittleFS filesystem
Command Line: C:\Users\Stephane\AppData\Local\Arduino15\packages\esp32\tools\esptool_py\4.6\esptool.exe --chip esp32s3 --port COM8 --baud 921600 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 80m --flash_size detect 6356992 C:\Users\Stephane\AppData\Local\Temp\tmp-6364-53B1Z1RPXuOM-.littlefs.bin

Wrote 4063232 bytes (886280 compressed) at 0x00610000 in 28.2 seconds (effective 1152.6 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

Completed upload.

👍🏻 👍🏻 👍🏻 👍🏻 

you are the best!

**Comment by stef-ladefense** [comment]
just a detail

Partitions: D:\Arduino\ESP32_RadioWeb\ESP32S3_RadioWeb_0_66\partitions.csv
Start: 0x610000
End: 0x9f0000

0x9f0000 is not end but length
end is 0x610000+0x9f0000=0x1000000
last adress is 0xffffff (start 0 -> 0x1000000-1 for 16Mb)

**Comment by earlephilhower** [comment]
Argh, thought your message was that it was working and this just missed the release.

Is the generated FS proper or busted?  I *think* it's broken and not the right size because the old code actually added fsStart to fsEnd before doing it's magic.

**Comment by earlephilhower** [comment]
#63 to fix

**Pull request merged**
